name: TOX Test

on: [push, pull_request]

jobs:
  tox:
    runs-on: docker
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13"]
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      run: |
        curl -LsSf https://astral.sh/uv/install.sh | sh
        echo "$HOME/.local/bin" >> "$GITHUB_PATH"
    - name: Test with tox
      run: |
        uv tool install tox --with tox-uv
        tox -e py$(echo ${{ matrix.python-version }} | tr -d .)
